import { CircuitComponent, JumperWire } from '../engine/componentTypes';
import { getHolePosition } from '../engine/breadboardModel';

export interface PresetCircuit {
  id: string;
  title: string;
  description: string;
  components: CircuitComponent[];
  wires: JumperWire[];
}

export function getPresetCircuits(): PresetCircuit[] {
  return [
    {
      id: 'led_basic',
      title: '1. Basic LED & Current Limiting Resistor',
      description: '9V Battery powering a 5mm Red LED protected by a 1kΩ resistor. Demonstrates Ohm’s law, forward voltage (1.9V), and safe 7.1mA operating current.',
      components: [
        {
          id: 'batt_1',
          type: 'BATTERY_9V',
          name: '9V Alkaline Battery',
          value: 9,
          unit: 'V',
          position: [-0.07, -0.04, 0.025],
          rotation: [0, 0, 0],
          modelUrl: '/models/power/battery_9v.glb',
          voltageDrop: 9,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'p1', name: '+', relativePos: [0.0064, 0, 0.025], connectedHoleId: 'TOP_POS_5' },
            { id: 'p2', name: '-', relativePos: [-0.0064, 0, 0.025], connectedHoleId: 'TOP_NEG_5' },
          ],
        },
        {
          id: 'res_1',
          type: 'RESISTOR',
          name: '1kΩ Resistor (1/4W)',
          value: 1000,
          unit: 'Ω',
          maxPowerRating: 0.25,
          position: [0.0, 0.012, 0.012],
          rotation: [0, 0, 0],
          modelUrl: '/models/components/resistor_1k.glb',
          voltageDrop: 0,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'r1', name: 'Pin 1', relativePos: [-0.00508, 0, 0], connectedHoleId: 'E15' },
            { id: 'r2', name: 'Pin 2', relativePos: [0.00508, 0, 0], connectedHoleId: 'E19' },
          ],
        },
        {
          id: 'led_1',
          type: 'LED',
          name: '5mm Red LED',
          value: 1,
          unit: 'pc',
          ledColor: 'RED',
          forwardVoltage: 1.9,
          position: [0.012, 0.012, 0.012],
          rotation: [0, 0, 0],
          modelUrl: '/models/components/led_5mm_red.glb',
          voltageDrop: 0,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'l1', name: 'ANODE', relativePos: [0.00127, 0, 0], connectedHoleId: 'D19' },
            { id: 'l2', name: 'CATHODE', relativePos: [-0.00127, 0, 0], connectedHoleId: 'D20' },
          ],
        },
      ],
      wires: [
        {
          id: 'w1',
          startHoleId: 'TOP_POS_15',
          endHoleId: 'A15',
          startPos: getHolePosition('TOP_POS_15') || [0, 0, 0],
          endPos: getHolePosition('A15') || [0, 0, 0],
          color: '#e63946', // Red
          current: 0,
          voltage: 0,
        },
        {
          id: 'w2',
          startHoleId: 'A20',
          endHoleId: 'TOP_NEG_20',
          startPos: getHolePosition('A20') || [0, 0, 0],
          endPos: getHolePosition('TOP_NEG_20') || [0, 0, 0],
          color: '#1d3557', // Dark Blue / Black
          current: 0,
          voltage: 0,
        },
      ],
    },
    {
      id: 'pot_lamp',
      title: '2. Variable Dimmer Lamp (Potentiometer)',
      description: '10kΩ Rotary Potentiometer driving an Incandescent Light Bulb. Turn the dial to smoothly throttle filament power and observe dynamic filament glow.',
      components: [
        {
          id: 'batt_pot',
          type: 'BATTERY_9V',
          name: '9V Battery',
          value: 9,
          unit: 'V',
          position: [-0.07, -0.04, 0.025],
          rotation: [0, 0, 0],
          modelUrl: '/models/power/battery_9v.glb',
          voltageDrop: 9,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'p1', name: '+', relativePos: [0.0064, 0, 0.025], connectedHoleId: 'TOP_POS_5' },
            { id: 'p2', name: '-', relativePos: [-0.0064, 0, 0.025], connectedHoleId: 'TOP_NEG_5' },
          ],
        },
        {
          id: 'pot_1',
          type: 'POTENTIOMETER',
          name: '10kΩ Rotary Potentiometer',
          value: 100, // Low resistance setting for high brightness
          unit: 'Ω',
          position: [-0.02, 0.012, 0.015],
          rotation: [0, 0, 0],
          modelUrl: '/models/components/potentiometer_10k.glb',
          voltageDrop: 0,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          state: { wiperRatio: 0.15 },
          pins: [
            { id: 'pt1', name: 'T1', relativePos: [-0.00254, -0.006, 0], connectedHoleId: 'E10' },
            { id: 'ptw', name: 'WIPER', relativePos: [0, -0.006, 0], connectedHoleId: 'E11' },
            { id: 'pt2', name: 'T2', relativePos: [0.00254, -0.006, 0], connectedHoleId: 'E12' },
          ],
        },
        {
          id: 'bulb_1',
          type: 'BULB_INCANDESCENT',
          name: 'Incandescent Indicator Bulb',
          value: 25,
          unit: 'Ω',
          position: [0.03, 0.012, 0.02],
          rotation: [0, 0, 0],
          modelUrl: '/models/components/bulb_incandescent.glb',
          voltageDrop: 0,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'b1', name: 'Terminal 1', relativePos: [-0.002, 0, 0], connectedHoleId: 'E22' },
            { id: 'b2', name: 'Terminal 2', relativePos: [0.002, 0, 0], connectedHoleId: 'E24' },
          ],
        },
      ],
      wires: [
        {
          id: 'wp1',
          startHoleId: 'TOP_POS_10',
          endHoleId: 'A10',
          startPos: getHolePosition('TOP_POS_10') || [0, 0, 0],
          endPos: getHolePosition('A10') || [0, 0, 0],
          color: '#e63946',
          current: 0,
          voltage: 0,
        },
        {
          id: 'wp2',
          startHoleId: 'B11',
          endHoleId: 'A22',
          startPos: getHolePosition('B11') || [0, 0, 0],
          endPos: getHolePosition('A22') || [0, 0, 0],
          color: '#f4a261', // Orange
          current: 0,
          voltage: 0,
        },
        {
          id: 'wp3',
          startHoleId: 'A24',
          endHoleId: 'TOP_NEG_24',
          startPos: getHolePosition('A24') || [0, 0, 0],
          endPos: getHolePosition('TOP_NEG_24') || [0, 0, 0],
          color: '#1d3557',
          current: 0,
          voltage: 0,
        },
      ],
    },
    {
      id: 'burnout_demo',
      title: '3. Thermal Overload & Resistor Burnout Demo',
      description: 'A 10Ω 1/4W resistor directly across 9V. Power dissipation reaches 8.1W (>32x rated limit), causing thermal runaway, component overheating, and catastrophic burnout.',
      components: [
        {
          id: 'batt_burn',
          type: 'BATTERY_9V',
          name: '9V Battery',
          value: 9,
          unit: 'V',
          position: [-0.07, -0.04, 0.025],
          rotation: [0, 0, 0],
          modelUrl: '/models/power/battery_9v.glb',
          voltageDrop: 9,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'p1', name: '+', relativePos: [0.0064, 0, 0.025], connectedHoleId: 'TOP_POS_5' },
            { id: 'p2', name: '-', relativePos: [-0.0064, 0, 0.025], connectedHoleId: 'TOP_NEG_5' },
          ],
        },
        {
          id: 'res_burn',
          type: 'RESISTOR',
          name: '10Ω Overloaded Resistor (0.25W Limit)',
          value: 10,
          unit: 'Ω',
          maxPowerRating: 0.25,
          position: [0.0, 0.012, 0.012],
          rotation: [0, 0, 0],
          modelUrl: '/models/components/resistor_1k.glb',
          voltageDrop: 0,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'r1', name: 'Pin 1', relativePos: [-0.00508, 0, 0], connectedHoleId: 'E15' },
            { id: 'r2', name: 'Pin 2', relativePos: [0.00508, 0, 0], connectedHoleId: 'E19' },
          ],
        },
      ],
      wires: [
        {
          id: 'wb1',
          startHoleId: 'TOP_POS_15',
          endHoleId: 'A15',
          startPos: getHolePosition('TOP_POS_15') || [0, 0, 0],
          endPos: getHolePosition('A15') || [0, 0, 0],
          color: '#e63946',
          current: 0,
          voltage: 0,
        },
        {
          id: 'wb2',
          startHoleId: 'A19',
          endHoleId: 'TOP_NEG_19',
          startPos: getHolePosition('A19') || [0, 0, 0],
          endPos: getHolePosition('TOP_NEG_19') || [0, 0, 0],
          color: '#1d3557',
          current: 0,
          voltage: 0,
        },
      ],
    },
    {
      id: 'speaker_osc',
      title: '4. Audio Tone Generator & 8Ω Speaker',
      description: '8Ω Dynamic Mini Speaker wired into an interactive pulsed signal. Demonstrates acoustic transducer physics and real-time browser audio playback.',
      components: [
        {
          id: 'batt_spk',
          type: 'BATTERY_9V',
          name: '9V Battery',
          value: 9,
          unit: 'V',
          position: [-0.07, -0.04, 0.025],
          rotation: [0, 0, 0],
          modelUrl: '/models/power/battery_9v.glb',
          voltageDrop: 9,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'p1', name: '+', relativePos: [0.0064, 0, 0.025], connectedHoleId: 'TOP_POS_5' },
            { id: 'p2', name: '-', relativePos: [-0.0064, 0, 0.025], connectedHoleId: 'TOP_NEG_5' },
          ],
        },
        {
          id: 'spk_1',
          type: 'SPEAKER',
          name: '8Ω Dynamic Mini Speaker',
          value: 8,
          unit: 'Ω',
          position: [0.03, 0.015, 0.02],
          rotation: [0, 0, 0],
          modelUrl: '/models/components/speaker_8ohm.glb',
          voltageDrop: 0,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          pins: [
            { id: 'sp1', name: '+', relativePos: [-0.008, 0, 0], connectedHoleId: 'E25' },
            { id: 'sp2', name: '-', relativePos: [0.008, 0, 0], connectedHoleId: 'E27' },
          ],
        },
        {
          id: 'btn_1',
          type: 'SWITCH_TACTILE',
          name: 'Tactile Pushbutton',
          value: 1,
          unit: 'sw',
          position: [-0.01, 0.012, 0.01],
          rotation: [0, 0, 0],
          modelUrl: '/models/components/button_tactile_6mm.glb',
          voltageDrop: 0,
          current: 0,
          powerDissipated: 0,
          temperature: 25,
          health: 'NORMAL',
          state: { isClosed: false },
          pins: [
            { id: 'b1', name: 'Pin 1', relativePos: [-0.002, 0, 0], connectedHoleId: 'E18' },
            { id: 'b2', name: 'Pin 2', relativePos: [0.002, 0, 0], connectedHoleId: 'E20' },
          ],
        },
      ],
      wires: [
        {
          id: 'ws1',
          startHoleId: 'TOP_POS_18',
          endHoleId: 'A18',
          startPos: getHolePosition('TOP_POS_18') || [0, 0, 0],
          endPos: getHolePosition('A18') || [0, 0, 0],
          color: '#e63946',
          current: 0,
          voltage: 0,
        },
        {
          id: 'ws2',
          startHoleId: 'A20',
          endHoleId: 'A25',
          startPos: getHolePosition('A20') || [0, 0, 0],
          endPos: getHolePosition('A25') || [0, 0, 0],
          color: '#2a9d8f', // Teal
          current: 0,
          voltage: 0,
        },
        {
          id: 'ws3',
          startHoleId: 'A27',
          endHoleId: 'TOP_NEG_27',
          startPos: getHolePosition('A27') || [0, 0, 0],
          endPos: getHolePosition('TOP_NEG_27') || [0, 0, 0],
          color: '#1d3557',
          current: 0,
          voltage: 0,
        },
      ],
    },
  ];
}
